### ISSUE TITLE
manifest.xml missing?

### ISSUE THREAD

**Issue by osa1** [fevieira27/MoveToBeActive#6]
I'm new at Garmin dev so sorry if I'm missing something.

When I try to build the project with

```
monkeyc -f monkey.jungle -o <output> -y <developer key> -d <device id>
```

I get this error:

```
ERROR: unknown:0: A valid 'project.manifest' property was not defined within a jungle file.
ERROR: monkey.jungle:1: The specified manifest file doesn't exist: manifest.xml
```

It seems like the manifest file specified in `monkey.jungle` is missing.

Would it be possible for you to commit that file too? Or is there another way to build this project and run using the SDK?

**Comment by fevieira27** [comment]
you can find your answer on the discussion below:
[](https://github.com/fevieira27/MoveToBeActive/discussions/4)

Since it's not really a bug, I'll close this one here, but feel free to join the discussion over there in case you still have problems after going through that topic.
