### ISSUE TITLE
option to disable the weather forecast

### ISSUE THREAD

**Issue by nosedive** [fevieira27/MoveToBeActive#7]
**Describe the feature that you'd like to see**
an option to disable weather forecast icon and temperature for cleaner simplified design like the setting if location name should be shown

**Watch Model**
VA4

btw thank you for all the hard work, best watchface ever :-D

**Comment by fevieira27** [comment]
Hi, will have a look at this. The only limiting factor would be the memory available in some older watches that I support (like Fenix 5 plus, fenix 6 and some Forerunners). But in case I can add this toggle without reaching memory limits on those watches, it will be implemented.

**Comment by nosedive** [comment]
👍 good news

**Comment by fevieira27** [comment]
Feature implemented on version 4.1.0, to be released later today. Sorry that it took a long time to add this, but it required a lot of effort to split the watch face between low-memory watches (like FR X45 series, MARQ 1 and Fenix 6s) that are not going to receive new features, like this one) and other watches that don't have memory issues yet and can have new features added.
